application: sitedrawer
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|xml))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|xml))

- url: .*
  script: main.py
